function selectall(m)

if dur(m.speech_pressure)<0.4 || ...
      strcmp(questdlg(['Processing of the complete '...
                      'signal may take a long time. ' ...
                      'Do you want to proceed?'],...
                      'Process the complete signal?', ...
                      'Yes','No','No'),'Yes')
  sel = m.sppres_selection;
  sel.left = m.speech_pressure.time.begin;
  sel.right = m.speech_pressure.time.end;
  m.ifwinsize = sel.right - sel.left;
  set(m, 'sppres_selection', sel);
end
